export const shopCategories = [
  { value: "clothing", label: "Clothing & Apparel" },
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "home_decor", label: "Home Decor" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "sports", label: "Sports & Outdoors" },
  { value: "books", label: "Books & Magazines" },
  { value: "toys", label: "Toys & Games" },
  { value: "furniture", label: "Furniture" },
  { value: "grocery", label: "Grocery & Gourmet Food" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "automotive", label: "Automotive Supplies" },
  { value: "music", label: "Music & Instruments" },
  { value: "pets", label: "Pet Supplies" },
  { value: "stationery", label: "Stationery & Office" },
  { value: "health", label: "Health & Wellness" },
  { value: "footwear", label: "Footwear" },
  { value: "kids", label: "Kids & Baby Products" },
  { value: "tools", label: "Tools & Home Improvement" },
  { value: "kitchen", label: "Kitchen & Dining" },
  { value: "art", label: "Art & Craft Supplies" },
  { value: "garden", label: "Garden & Outdoor" },
  { value: "travel", label: "Travel & Luggage" },
  { value: "gaming", label: "Video Games & Consoles" },
  { value: "office_supplies", label: "Office Supplies" },
  { value: "party", label: "Party Supplies" },
  { value: "baby", label: "Baby & Maternity" },
  { value: "hardware", label: "Hardware & Fasteners" },
  { value: "lighting", label: "Lighting & Fixtures" },
  { value: "bedding", label: "Bedding & Bath" },
  { value: "collectibles", label: "Collectibles & Memorabilia" }
];
